server:
  port: 8080

logging:
  level:
    root: INFO
#    org.springframework.jdbc: DEBUG

db:
  driver: 'org.mariadb.jdbc.Driver'
  url: 'jdbc:mysql://localhost:3306/test'
  username: user
  password: password
  pool:
    min:
      idle: 10
    max:
      size: 50

