server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/test
    username: user
    password: password
    pool:
      enabled: true
      max-size: 200
      initial-size: 50
      max-acquire-time: 5s
      max-life-time: 2h
      max-create-connection-time: 5s
      max-idle-time: 10m
    properties:
      autoCommit: false

logging:
  level:
    root: INFO
#    org.springframework.r2dbc: DEBUG
#    io.r2dbc.pool: DEBUG
#    org.mariadb.r2dbc: DEBUG

